import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router';

import { paths } from '@/app/router/paths';
import { OutputTypeSelector } from '@/features/send-quote/OutputTypeSelector';
import { buildPricingRows, getPricingTotals, isBelowMarginFloor } from '@/entities/quote/lib/pricing';
import type { QuoteOutputType } from '@/entities/quote/model/types';
import { useQuoteDetail } from '@/pages/quote-detail/model/QuoteDetailContext';
import { useCommunicationStore } from '@/pages/quote-detail/model/communicationStore';
import { pluralSuffix } from '@/shared/lib/format';
import { Button } from '@/shared/ui/Button';
import { Modal } from '@/shared/ui/Modal';
import { useToast } from '@/shared/ui/Toast';
import { QuoteDocument } from '@/widgets/quote-document/QuoteDocument';

const SEND_LABEL: Record<QuoteOutputType, string> = {
  mtml: 'Send Quote to portal',
  email: 'Send Quote',
  customerExcel: 'Send populated Excel',
};

export const SendQuoteTab = () => {
  const { quote, catalog, actions } = useQuoteDetail();
  const { quoteId = '' } = useParams();
  const navigate = useNavigate();
  const toast = useToast();
  const openPanel = useCommunicationStore((state) => state.open);

  const [isConfirmOpen, setConfirmOpen] = useState(false);

  const rows = useMemo(() => buildPricingRows(quote, catalog), [catalog, quote]);
  const totals = useMemo(() => getPricingTotals(rows, quote), [quote, rows]);

  const outputType: QuoteOutputType =
    quote.outputType ?? (quote.header.fileType === 'MTML' ? 'mtml' : 'email');
  const isBlocked = isBelowMarginFloor(quote) || Boolean(quote.sentAt);

  const send = async () => {
    setConfirmOpen(false);
    await actions.sendQuote({ outputType });
    toast.show(outputType === 'mtml' ? 'Quote posted to portal' : 'Quote email sent via Outlook · cc added');
    openPanel('customer');
    setTimeout(() => void navigate(paths.rfqTab(quoteId, 'order')), 900);
  };

  const handleSend = () => {
    if (totals.unpricedCount > 0) {
      setConfirmOpen(true);
      return;
    }
    void send();
  };

  return (
    <>
      <div className="flex flex-wrap items-center gap-3 px-4 pt-3.5 pb-2.5">
        <span className="text-[13px] text-ink2">
          <b>
            {totals.pricedCount} of {rows.length}
          </b>{' '}
          lines priced
          {totals.unpricedCount > 0
            ? ` · ${totals.unpricedCount} without price — will go to the quote as clarification`
            : ' · ready to send'}
        </span>
        <span className="ml-auto" />
        <Button onClick={() => toast.show('PDF export is generated by the backend')}>
          Download PDF
        </Button>
        <Button onClick={() => toast.show('Excel export is generated by the backend')}>
          Download Excel
        </Button>
        <Button variant="primary" size="lg" disabled={isBlocked} onClick={handleSend}>
          {quote.sentAt ? `Sent ${quote.sentAt}` : SEND_LABEL[outputType]}
        </Button>
      </div>

      <OutputTypeSelector />
      <QuoteDocument />

      <Modal
        open={isConfirmOpen}
        onClose={() => setConfirmOpen(false)}
        title="Send as draft quote?"
        width="440px"
        footer={
          <>
            <span className="ml-auto" />
            <Button onClick={() => setConfirmOpen(false)}>Cancel</Button>
            <Button variant="primary" onClick={send}>
              Send with clarifications
            </Button>
          </>
        }
      >
        <p className="m-0 text-sm text-ink2">
          {totals.unpricedCount} line{pluralSuffix(totals.unpricedCount)} have zero price or are
          unresolved. Send as a draft quote with clarifications?
        </p>
      </Modal>
    </>
  );
};
